/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GlobalArtha;

import java.awt.Frame;
import java.io.InputStream;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import laporan.fungsicetak;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Bima PC
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
        Locale locale = new Locale ("id","ID");
        Locale.setDefault(locale);
    }
    
    public void tanggal(){
        java.sql.Connection con = null;
          try {
              String jdbcDriver = "com.mysql.jdbc.Driver";
              Class.forName(jdbcDriver);
              
              String url = "jdbc:mysql://localhost:3306/tokolaptop";
              String user = "root";
              String pass = "";
              
              con = DriverManager.getConnection(url, user, pass);
              Statement stm = con.createStatement();
              
              try{
                  String report = ("./src/report/reportPenjualan.jrxml");
                  HashMap hash = new HashMap();
                  
                  hash.put("tgl1", tTgl1.getText());
                  hash.put("tgl2", tTgl2.getText());
                  JasperReport JRpt = JasperCompileManager.compileReport(report);
                  JasperPrint Jprint = JasperFillManager.fillReport(JRpt, hash, con);
                  JasperViewer.viewReport(Jprint, false);
              }catch (Exception rptexcpt){
                  System.out.println("Report Gagal Karena : " + rptexcpt);
              }
          }catch (Exception e){
              System.out.println(e);
          }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jTglPenjualan1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        tTgl1 = new javax.swing.JTextField();
        tTgl2 = new javax.swing.JTextField();
        tLapBarang7 = new javax.swing.JLabel();
        tLapBarang8 = new javax.swing.JLabel();
        tLapBarang9 = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        tabPanel = new javax.swing.JPanel();
        bMaster = new javax.swing.JButton();
        bTransaksi = new javax.swing.JButton();
        bLaporan = new javax.swing.JButton();
        bLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        masterPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bBarang = new javax.swing.JButton();
        bPelanggan = new javax.swing.JButton();
        tBarang = new javax.swing.JLabel();
        tPelanggan = new javax.swing.JLabel();
        bKaryawan = new javax.swing.JButton();
        tKaryawan = new javax.swing.JLabel();
        transaksiPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bPembelian = new javax.swing.JButton();
        tPenjualan = new javax.swing.JLabel();
        laporanPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        bLapPenjualan = new javax.swing.JButton();
        bLapKaryawan = new javax.swing.JButton();
        bLapBarang = new javax.swing.JButton();
        bLapPelanggan = new javax.swing.JButton();
        tLapBarang = new javax.swing.JLabel();
        tLapPelanggan = new javax.swing.JLabel();
        tLapKaryawan = new javax.swing.JLabel();
        tLapPenjualan = new javax.swing.JLabel();

        jTglPenjualan1.setBackground(new java.awt.Color(32, 191, 107));

        jButton3.setText("CETAK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tLapBarang7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        tLapBarang7.setForeground(new java.awt.Color(255, 255, 255));
        tLapBarang7.setText("SAMPAI");
        tLapBarang7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tLapBarang7MouseClicked(evt);
            }
        });

        tLapBarang8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        tLapBarang8.setForeground(new java.awt.Color(255, 255, 255));
        tLapBarang8.setText("DARI");
        tLapBarang8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tLapBarang8MouseClicked(evt);
            }
        });

        tLapBarang9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tLapBarang9.setForeground(new java.awt.Color(255, 255, 255));
        tLapBarang9.setText("TANGGAL PENJUALAN");
        tLapBarang9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tLapBarang9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jTglPenjualan1Layout = new javax.swing.GroupLayout(jTglPenjualan1);
        jTglPenjualan1.setLayout(jTglPenjualan1Layout);
        jTglPenjualan1Layout.setHorizontalGroup(
            jTglPenjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTglPenjualan1Layout.createSequentialGroup()
                .addGroup(jTglPenjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jTglPenjualan1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(jTglPenjualan1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jTglPenjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tLapBarang7)
                            .addComponent(tLapBarang8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jTglPenjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tTgl2, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(tTgl1))))
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTglPenjualan1Layout.createSequentialGroup()
                .addGap(0, 107, Short.MAX_VALUE)
                .addComponent(tLapBarang9)
                .addGap(103, 103, 103))
        );
        jTglPenjualan1Layout.setVerticalGroup(
            jTglPenjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTglPenjualan1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tLapBarang9)
                .addGap(57, 57, 57)
                .addGroup(jTglPenjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tTgl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tLapBarang8))
                .addGap(36, 36, 36)
                .addGroup(jTglPenjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tTgl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tLapBarang7))
                .addGap(50, 50, 50)
                .addComponent(jButton3)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTglPenjualan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTglPenjualan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("skripsi");

        menuPanel.setBackground(new java.awt.Color(32, 191, 107));

        tabPanel.setBackground(new java.awt.Color(32, 191, 107));
        tabPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        bMaster.setText("MASTER");
        bMaster.setIconTextGap(20);
        bMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMasterActionPerformed(evt);
            }
        });

        bTransaksi.setText("TRANSAKSI");
        bTransaksi.setIconTextGap(20);
        bTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTransaksiActionPerformed(evt);
            }
        });

        bLaporan.setText("LAPORAN");
        bLaporan.setIconTextGap(20);
        bLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLaporanActionPerformed(evt);
            }
        });

        bLogout.setText("LOGOUT");
        bLogout.setIconTextGap(20);
        bLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GLOBAL ARTHA COMPUTER");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo.png"))); // NOI18N

        javax.swing.GroupLayout tabPanelLayout = new javax.swing.GroupLayout(tabPanel);
        tabPanel.setLayout(tabPanelLayout);
        tabPanelLayout.setHorizontalGroup(
            tabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bMaster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bTransaksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bLaporan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabPanelLayout.createSequentialGroup()
                        .addGap(0, 29, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(17, 17, 17)))
                .addContainerGap())
            .addGroup(tabPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabPanelLayout.setVerticalGroup(
            tabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(80, 80, 80)
                .addComponent(bMaster)
                .addGap(40, 40, 40)
                .addComponent(bTransaksi)
                .addGap(40, 40, 40)
                .addComponent(bLaporan)
                .addGap(40, 40, 40)
                .addComponent(bLogout)
                .addContainerGap())
        );

        mainPanel.setBackground(new java.awt.Color(32, 191, 107));
        mainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        mainPanel.setLayout(new java.awt.CardLayout());

        masterPanel.setBackground(new java.awt.Color(32, 191, 107));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MENU MASTER");

        bBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-laptop-100.png"))); // NOI18N
        bBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBarangActionPerformed(evt);
            }
        });

        bPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-user-100.png"))); // NOI18N
        bPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPelangganActionPerformed(evt);
            }
        });

        tBarang.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tBarang.setForeground(new java.awt.Color(255, 255, 255));
        tBarang.setText("BARANG");
        tBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tBarangMouseClicked(evt);
            }
        });

        tPelanggan.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        tPelanggan.setText("PELANGGAN");
        tPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tPelangganMouseClicked(evt);
            }
        });

        bKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-name-tag-100.png"))); // NOI18N
        bKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKaryawanActionPerformed(evt);
            }
        });

        tKaryawan.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tKaryawan.setForeground(new java.awt.Color(255, 255, 255));
        tKaryawan.setText("KARYAWAN");
        tKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tKaryawanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout masterPanelLayout = new javax.swing.GroupLayout(masterPanel);
        masterPanel.setLayout(masterPanelLayout);
        masterPanelLayout.setHorizontalGroup(
            masterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(525, Short.MAX_VALUE))
            .addGroup(masterPanelLayout.createSequentialGroup()
                .addGroup(masterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(masterPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(bBarang))
                    .addGroup(masterPanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(tBarang)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(masterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(masterPanelLayout.createSequentialGroup()
                        .addComponent(tKaryawan)
                        .addGap(97, 97, 97)
                        .addComponent(tPelanggan)
                        .addGap(66, 66, 66))
                    .addGroup(masterPanelLayout.createSequentialGroup()
                        .addComponent(bKaryawan)
                        .addGap(74, 74, 74)
                        .addComponent(bPelanggan)
                        .addGap(51, 51, 51))))
        );
        masterPanelLayout.setVerticalGroup(
            masterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(224, 224, 224)
                .addGroup(masterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(masterPanelLayout.createSequentialGroup()
                        .addGroup(masterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bBarang)
                            .addComponent(bPelanggan))
                        .addGap(18, 18, 18)
                        .addGroup(masterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tBarang)
                            .addComponent(tPelanggan)))
                    .addGroup(masterPanelLayout.createSequentialGroup()
                        .addComponent(bKaryawan)
                        .addGap(18, 18, 18)
                        .addComponent(tKaryawan)))
                .addContainerGap(260, Short.MAX_VALUE))
        );

        mainPanel.add(masterPanel, "card2");

        transaksiPanel.setBackground(new java.awt.Color(32, 191, 107));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MENU TRANSAKSI");

        bPembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-buy-100.png"))); // NOI18N
        bPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPembelianActionPerformed(evt);
            }
        });

        tPenjualan.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tPenjualan.setForeground(new java.awt.Color(255, 255, 255));
        tPenjualan.setText("Penjualan");
        tPenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tPenjualanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout transaksiPanelLayout = new javax.swing.GroupLayout(transaksiPanel);
        transaksiPanel.setLayout(transaksiPanelLayout);
        transaksiPanelLayout.setHorizontalGroup(
            transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(499, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transaksiPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bPembelian)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transaksiPanelLayout.createSequentialGroup()
                        .addComponent(tPenjualan)
                        .addGap(22, 22, 22)))
                .addGap(261, 261, 261))
        );
        transaksiPanelLayout.setVerticalGroup(
            transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(221, 221, 221)
                .addComponent(bPembelian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tPenjualan)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        mainPanel.add(transaksiPanel, "card3");

        laporanPanel.setBackground(new java.awt.Color(32, 191, 107));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MENU LAPORAN");

        bLapPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-sell-100.png"))); // NOI18N
        bLapPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLapPenjualanActionPerformed(evt);
            }
        });

        bLapKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-name-tag-100.png"))); // NOI18N
        bLapKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLapKaryawanActionPerformed(evt);
            }
        });

        bLapBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-laptop-100.png"))); // NOI18N
        bLapBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLapBarangActionPerformed(evt);
            }
        });

        bLapPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-user-100.png"))); // NOI18N
        bLapPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLapPelangganActionPerformed(evt);
            }
        });

        tLapBarang.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tLapBarang.setForeground(new java.awt.Color(255, 255, 255));
        tLapBarang.setText("BARANG");
        tLapBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tLapBarangMouseClicked(evt);
            }
        });

        tLapPelanggan.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tLapPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        tLapPelanggan.setText("PELANGGAN");
        tLapPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tLapPelangganMouseClicked(evt);
            }
        });

        tLapKaryawan.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tLapKaryawan.setForeground(new java.awt.Color(255, 255, 255));
        tLapKaryawan.setText("KARYAWAN");
        tLapKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tLapKaryawanMouseClicked(evt);
            }
        });

        tLapPenjualan.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tLapPenjualan.setForeground(new java.awt.Color(255, 255, 255));
        tLapPenjualan.setText("PENJUALAN");
        tLapPenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tLapPenjualanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout laporanPanelLayout = new javax.swing.GroupLayout(laporanPanel);
        laporanPanel.setLayout(laporanPanelLayout);
        laporanPanelLayout.setHorizontalGroup(
            laporanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanPanelLayout.createSequentialGroup()
                .addGroup(laporanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(laporanPanelLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(tLapBarang)
                        .addGap(138, 138, 138)
                        .addComponent(tLapKaryawan))
                    .addGroup(laporanPanelLayout.createSequentialGroup()
                        .addGroup(laporanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(laporanPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4))
                            .addGroup(laporanPanelLayout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addGroup(laporanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bLapPelanggan)
                                    .addComponent(bLapBarang))))
                        .addGap(101, 101, 101)
                        .addGroup(laporanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bLapPenjualan)
                            .addComponent(bLapKaryawan))))
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laporanPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tLapPelanggan)
                .addGap(128, 128, 128)
                .addComponent(tLapPenjualan)
                .addGap(164, 164, 164))
        );
        laporanPanelLayout.setVerticalGroup(
            laporanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laporanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(104, 104, 104)
                .addGroup(laporanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laporanPanelLayout.createSequentialGroup()
                        .addComponent(bLapBarang)
                        .addGap(18, 18, 18)
                        .addComponent(tLapBarang))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laporanPanelLayout.createSequentialGroup()
                        .addComponent(bLapKaryawan)
                        .addGap(18, 18, 18)
                        .addComponent(tLapKaryawan)))
                .addGap(96, 96, 96)
                .addGroup(laporanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bLapPenjualan)
                    .addComponent(bLapPelanggan))
                .addGap(18, 18, 18)
                .addGroup(laporanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tLapPenjualan)
                    .addComponent(tLapPelanggan))
                .addGap(0, 134, Short.MAX_VALUE))
        );

        mainPanel.add(laporanPanel, "card4");

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBarangActionPerformed
        // TODO add your handling code here:
        
        //membuka form barang
        new FormBarang().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bBarangActionPerformed

    private void bMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMasterActionPerformed
        // TODO add your handling code here:
        
        //remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        //add panel
        mainPanel.add(masterPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        
    }//GEN-LAST:event_bMasterActionPerformed

    private void bTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTransaksiActionPerformed
        // TODO add your handling code here:
        
        //remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        //add panel
        mainPanel.add(transaksiPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        
    }//GEN-LAST:event_bTransaksiActionPerformed

    private void bLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLaporanActionPerformed
        // TODO add your handling code here:
        
        //remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        //add panel
        mainPanel.add(laporanPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        
    }//GEN-LAST:event_bLaporanActionPerformed

    private void bLapPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLapPenjualanActionPerformed
        // TODO add your handling code here:
        new ParameterTanggal().setVisible(true);
        
    }//GEN-LAST:event_bLapPenjualanActionPerformed

    private void bPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPelangganActionPerformed
        // TODO add your handling code here:
        
        //membuka form pelanggan
        new FormPelanggan().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bPelangganActionPerformed

    private void tPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tPelangganMouseClicked
        // TODO add your handling code here:
        
        //membuka form pelanggan
        new FormPelanggan().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tPelangganMouseClicked

    private void tBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tBarangMouseClicked
        // TODO add your handling code here:
        
        //membuka form barang
        new FormBarang().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tBarangMouseClicked

    private void bLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutActionPerformed
        // TODO add your handling code here:
        
        //keluar akun
        new FormLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bLogoutActionPerformed

    private void bPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPembelianActionPerformed
        // TODO add your handling code here:
        new FormTransaksi().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bPembelianActionPerformed

    private void tPenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tPenjualanMouseClicked
        // TODO add your handling code here:
        new FormTransaksi().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tPenjualanMouseClicked

    private void bLapBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLapBarangActionPerformed
        // TODO add your handling code here:
        java.sql.Connection con = null;
          try {
              String jdbcDriver = "com.mysql.jdbc.Driver";
              Class.forName(jdbcDriver);
              
              String url = "jdbc:mysql://localhost:3306/tokolaptop";
              String user = "root";
              String pass = "";
              
              con = DriverManager.getConnection(url, user, pass);
              Statement stm = con.createStatement();
              
              try{
                  String RealPath ="src/icon/";
                  String report = ("./src/report/reportBarang.jrxml");
                  HashMap hash = new HashMap();
                  
                  hash.put("RealPath",RealPath);
                  InputStream gambar;
                  gambar = getClass().getResourceAsStream("logo.png");
                  JasperReport JRpt = JasperCompileManager.compileReport(report);
                  JasperPrint Jprint = JasperFillManager.fillReport(JRpt, hash, con);
                  JasperViewer.viewReport(Jprint, false);
              }catch (Exception rptexcpt){
                  System.out.println("Report Gagal Karena : " + rptexcpt);
              }
          }catch (Exception e){
              System.out.println(e);
          }        
    }//GEN-LAST:event_bLapBarangActionPerformed

    private void bKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKaryawanActionPerformed
        // TODO add your handling code here:
        new FormKaryawan().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bKaryawanActionPerformed

    private void tKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tKaryawanMouseClicked
        // TODO add your handling code here:
        new FormKaryawan().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tKaryawanMouseClicked

    private void bLapKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLapKaryawanActionPerformed
        // TODO add your handling code here:
        java.sql.Connection con = null;
          try {
              String jdbcDriver = "com.mysql.jdbc.Driver";
              Class.forName(jdbcDriver);
              
              String url = "jdbc:mysql://localhost:3306/tokolaptop";
              String user = "root";
              String pass = "";
              
              con = DriverManager.getConnection(url, user, pass);
              Statement stm = con.createStatement();
              
              try{
                  String RealPath ="src/icon/";
                  String report = ("./src/report/reportKaryawan.jrxml");
                  HashMap hash = new HashMap();
                  
                  hash.put("RealPath",RealPath);
                  InputStream gambar;
                  gambar = getClass().getResourceAsStream("logo.png");
                  JasperReport JRpt = JasperCompileManager.compileReport(report);
                  JasperPrint Jprint = JasperFillManager.fillReport(JRpt, hash, con);
                  JasperViewer.viewReport(Jprint, false);
              }catch (Exception rptexcpt){
                  System.out.println("Report Gagal Karena : " + rptexcpt);
              }
          }catch (Exception e){
              System.out.println(e);
          }
    }//GEN-LAST:event_bLapKaryawanActionPerformed

    private void tLapKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tLapKaryawanMouseClicked
        // TODO add your handling code here:
        java.sql.Connection con = null;
          try {
              String jdbcDriver = "com.mysql.jdbc.Driver";
              Class.forName(jdbcDriver);
              
              String url = "jdbc:mysql://localhost:3306/tokolaptop";
              String user = "root";
              String pass = "";
              
              con = DriverManager.getConnection(url, user, pass);
              Statement stm = con.createStatement();
              
              try{
                  String RealPath ="src/icon/";
                  String report = ("./src/report/reportKaryawan.jrxml");
                  HashMap hash = new HashMap();
                  
                  hash.put("RealPath",RealPath);
                  InputStream gambar;
                  gambar = getClass().getResourceAsStream("logo.png");
                  JasperReport JRpt = JasperCompileManager.compileReport(report);
                  JasperPrint Jprint = JasperFillManager.fillReport(JRpt, hash, con);
                  JasperViewer.viewReport(Jprint, false);
              }catch (Exception rptexcpt){
                  System.out.println("Report Gagal Karena : " + rptexcpt);
              }
          }catch (Exception e){
              System.out.println(e);
          }       
        
    }//GEN-LAST:event_tLapKaryawanMouseClicked

    private void tLapBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tLapBarangMouseClicked
        // TODO add your handling code here:
        java.sql.Connection con = null;
          try {
              String jdbcDriver = "com.mysql.jdbc.Driver";
              Class.forName(jdbcDriver);
              
              String url = "jdbc:mysql://localhost:3306/tokolaptop";
              String user = "root";
              String pass = "";
              
              con = DriverManager.getConnection(url, user, pass);
              Statement stm = con.createStatement();
              
              try{
                  String RealPath ="src/icon/";
                  String report = ("./src/report/reportBarang.jrxml");
                  HashMap hash = new HashMap();
                  
                  hash.put("RealPath",RealPath);
                  InputStream gambar;
                  gambar = getClass().getResourceAsStream("logo.png");
                  JasperReport JRpt = JasperCompileManager.compileReport(report);
                  JasperPrint Jprint = JasperFillManager.fillReport(JRpt, hash, con);
                  JasperViewer.viewReport(Jprint, false);
              }catch (Exception rptexcpt){
                  System.out.println("Report Gagal Karena : " + rptexcpt);
              }
          }catch (Exception e){
              System.out.println(e);
          }
        
    }//GEN-LAST:event_tLapBarangMouseClicked

    private void bLapPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLapPelangganActionPerformed
        // TODO add your handling code here:
        java.sql.Connection con = null;
          try {
              String jdbcDriver = "com.mysql.jdbc.Driver";
              Class.forName(jdbcDriver);
              
              String url = "jdbc:mysql://localhost:3306/tokolaptop";
              String user = "root";
              String pass = "";
              
              con = DriverManager.getConnection(url, user, pass);
              Statement stm = con.createStatement();
              
              try{
                  String RealPath ="src/icon/";
                  String report = ("./src/report/reportPelanggan.jrxml");
                  HashMap hash = new HashMap();
                  
                  hash.put("RealPath",RealPath);
                  InputStream gambar;
                  gambar = getClass().getResourceAsStream("logo.png");
                  JasperReport JRpt = JasperCompileManager.compileReport(report);
                  JasperPrint Jprint = JasperFillManager.fillReport(JRpt, hash, con);
                  JasperViewer.viewReport(Jprint, false);
              }catch (Exception rptexcpt){
                  System.out.println("Report Gagal Karena : " + rptexcpt);
              }
          }catch (Exception e){
              System.out.println(e);
          }
        
    }//GEN-LAST:event_bLapPelangganActionPerformed

    private void tLapPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tLapPelangganMouseClicked
        // TODO add your handling code here:
        java.sql.Connection con = null;
          try {
              String jdbcDriver = "com.mysql.jdbc.Driver";
              Class.forName(jdbcDriver);
              
              String url = "jdbc:mysql://localhost:3306/tokolaptop";
              String user = "root";
              String pass = "";
              
              con = DriverManager.getConnection(url, user, pass);
              Statement stm = con.createStatement();
              
              try{
                  String RealPath ="src/icon/";
                  String report = ("./src/report/reportPelanggan.jrxml");
                  HashMap hash = new HashMap();
                  
                  hash.put("RealPath",RealPath);
                  InputStream gambar;
                  gambar = getClass().getResourceAsStream("logo.png");
                  JasperReport JRpt = JasperCompileManager.compileReport(report);
                  JasperPrint Jprint = JasperFillManager.fillReport(JRpt, hash, con);
                  JasperViewer.viewReport(Jprint, false);
              }catch (Exception rptexcpt){
                  System.out.println("Report Gagal Karena : " + rptexcpt);
              }
          }catch (Exception e){
              System.out.println(e);
          }
        
    }//GEN-LAST:event_tLapPelangganMouseClicked

    private void tLapPenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tLapPenjualanMouseClicked
        // TODO add your handling code here:
        java.sql.Connection con = null;
          try {
              String jdbcDriver = "com.mysql.jdbc.Driver";
              Class.forName(jdbcDriver);
              
              String url = "jdbc:mysql://localhost:3306/tokolaptop";
              String user = "root";
              String pass = "";
              
              con = DriverManager.getConnection(url, user, pass);
              Statement stm = con.createStatement();
              
              try{
                  String RealPath ="src/icon/";
                  String report = ("./src/report/reportPenjualan.jrxml");
                  HashMap hash = new HashMap();
                  
                  hash.put("RealPath",RealPath);
                  InputStream gambar;
                  gambar = getClass().getResourceAsStream("logo.png");
                  JasperReport JRpt = JasperCompileManager.compileReport(report);
                  JasperPrint Jprint = JasperFillManager.fillReport(JRpt, hash, con);
                  JasperViewer.viewReport(Jprint, false);
              }catch (Exception rptexcpt){
                  System.out.println("Report Gagal Karena : " + rptexcpt);
              }
          }catch (Exception e){
              System.out.println(e);
          }
        
    }//GEN-LAST:event_tLapPenjualanMouseClicked

    private void tLapBarang7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tLapBarang7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tLapBarang7MouseClicked

    private void tLapBarang8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tLapBarang8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tLapBarang8MouseClicked

    private void tLapBarang9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tLapBarang9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tLapBarang9MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBarang;
    private javax.swing.JButton bKaryawan;
    private javax.swing.JButton bLapBarang;
    private javax.swing.JButton bLapKaryawan;
    private javax.swing.JButton bLapPelanggan;
    private javax.swing.JButton bLapPenjualan;
    private javax.swing.JButton bLaporan;
    private javax.swing.JButton bLogout;
    private javax.swing.JButton bMaster;
    private javax.swing.JButton bPelanggan;
    private javax.swing.JButton bPembelian;
    private javax.swing.JButton bTransaksi;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jTglPenjualan1;
    private javax.swing.JPanel laporanPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel masterPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel tBarang;
    private javax.swing.JLabel tKaryawan;
    private javax.swing.JLabel tLapBarang;
    private javax.swing.JLabel tLapBarang7;
    private javax.swing.JLabel tLapBarang8;
    private javax.swing.JLabel tLapBarang9;
    private javax.swing.JLabel tLapKaryawan;
    private javax.swing.JLabel tLapPelanggan;
    private javax.swing.JLabel tLapPenjualan;
    private javax.swing.JLabel tPelanggan;
    private javax.swing.JLabel tPenjualan;
    private javax.swing.JTextField tTgl1;
    private javax.swing.JTextField tTgl2;
    private javax.swing.JPanel tabPanel;
    private javax.swing.JPanel transaksiPanel;
    // End of variables declaration//GEN-END:variables
}
