/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GlobalArtha;

import java.io.InputStream;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Bima PC
 */
public class ParameterTanggal extends javax.swing.JFrame {

    /**
     * Creates new form ParameterTanggal
     */
    public ParameterTanggal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTglPenjualan1 = new javax.swing.JPanel();
        bCetak = new javax.swing.JButton();
        tTgl1 = new javax.swing.JTextField();
        tTgl2 = new javax.swing.JTextField();
        tLapBarang7 = new javax.swing.JLabel();
        tLapBarang8 = new javax.swing.JLabel();
        tLapBarang9 = new javax.swing.JLabel();
        tLapBarang10 = new javax.swing.JLabel();
        tLapBarang11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTglPenjualan1.setBackground(new java.awt.Color(32, 191, 107));

        bCetak.setText("CETAK");
        bCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCetakActionPerformed(evt);
            }
        });

        tLapBarang7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        tLapBarang7.setForeground(new java.awt.Color(255, 255, 255));
        tLapBarang7.setText("SAMPAI");
        tLapBarang7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tLapBarang7MouseClicked(evt);
            }
        });

        tLapBarang8.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        tLapBarang8.setForeground(new java.awt.Color(255, 255, 255));
        tLapBarang8.setText("yyyy-MM-dd");
        tLapBarang8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tLapBarang8MouseClicked(evt);
            }
        });

        tLapBarang9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tLapBarang9.setForeground(new java.awt.Color(255, 255, 255));
        tLapBarang9.setText("TANGGAL PENJUALAN");
        tLapBarang9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tLapBarang9MouseClicked(evt);
            }
        });

        tLapBarang10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        tLapBarang10.setForeground(new java.awt.Color(255, 255, 255));
        tLapBarang10.setText("DARI");
        tLapBarang10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tLapBarang10MouseClicked(evt);
            }
        });

        tLapBarang11.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        tLapBarang11.setForeground(new java.awt.Color(255, 255, 255));
        tLapBarang11.setText("yyyy-MM-dd");
        tLapBarang11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tLapBarang11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jTglPenjualan1Layout = new javax.swing.GroupLayout(jTglPenjualan1);
        jTglPenjualan1.setLayout(jTglPenjualan1Layout);
        jTglPenjualan1Layout.setHorizontalGroup(
            jTglPenjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTglPenjualan1Layout.createSequentialGroup()
                .addGap(0, 107, Short.MAX_VALUE)
                .addComponent(tLapBarang9)
                .addGap(103, 103, 103))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTglPenjualan1Layout.createSequentialGroup()
                .addGroup(jTglPenjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jTglPenjualan1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bCetak))
                    .addGroup(jTglPenjualan1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(tLapBarang7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jTglPenjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tTgl2, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(tTgl1)))
                    .addGroup(jTglPenjualan1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jTglPenjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tLapBarang11)
                            .addComponent(tLapBarang8))))
                .addGap(49, 49, 49))
            .addGroup(jTglPenjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jTglPenjualan1Layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(tLapBarang10)
                    .addContainerGap(306, Short.MAX_VALUE)))
        );
        jTglPenjualan1Layout.setVerticalGroup(
            jTglPenjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTglPenjualan1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tLapBarang9)
                .addGap(57, 57, 57)
                .addComponent(tTgl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(tLapBarang8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jTglPenjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tTgl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tLapBarang7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tLapBarang11)
                .addGap(24, 24, 24)
                .addComponent(bCetak)
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(jTglPenjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jTglPenjualan1Layout.createSequentialGroup()
                    .addGap(104, 104, 104)
                    .addComponent(tLapBarang10)
                    .addContainerGap(177, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTglPenjualan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTglPenjualan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCetakActionPerformed
        // TODO add your handling code here:
        java.sql.Connection con = null;
          try {
              String jdbcDriver = "com.mysql.jdbc.Driver";
              Class.forName(jdbcDriver);
              
              String url = "jdbc:mysql://localhost:3306/tokolaptop";
              String user = "root";
              String pass = "";
              
              con = DriverManager.getConnection(url, user, pass);
              Statement stm = con.createStatement();
              
              try{
                  String RealPath ="src/icon/";
                  String report = ("./src/report/reportPenjualan.jrxml");
                  HashMap hash = new HashMap();
                  
                  hash.put("tgl1", tTgl1.getText());
                  hash.put("tgl2", tTgl2.getText());
                  hash.put("RealPath",RealPath);
                  InputStream gambar;
                  gambar = getClass().getResourceAsStream("logo.png");
                  JasperReport JRpt = JasperCompileManager.compileReport(report);
                  JasperPrint Jprint = JasperFillManager.fillReport(JRpt, hash, con);
                  JasperViewer.viewReport(Jprint, false);
              }catch (Exception rptexcpt){
                  System.out.println("Report Gagal Karena : " + rptexcpt);
              }
          }catch (Exception e){
              System.out.println(e);
          }
    }//GEN-LAST:event_bCetakActionPerformed

    private void tLapBarang7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tLapBarang7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tLapBarang7MouseClicked

    private void tLapBarang8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tLapBarang8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tLapBarang8MouseClicked

    private void tLapBarang9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tLapBarang9MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tLapBarang9MouseClicked

    private void tLapBarang10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tLapBarang10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tLapBarang10MouseClicked

    private void tLapBarang11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tLapBarang11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tLapBarang11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParameterTanggal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParameterTanggal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParameterTanggal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParameterTanggal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParameterTanggal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCetak;
    private javax.swing.JPanel jTglPenjualan1;
    private javax.swing.JLabel tLapBarang10;
    private javax.swing.JLabel tLapBarang11;
    private javax.swing.JLabel tLapBarang7;
    private javax.swing.JLabel tLapBarang8;
    private javax.swing.JLabel tLapBarang9;
    private javax.swing.JTextField tTgl1;
    private javax.swing.JTextField tTgl2;
    // End of variables declaration//GEN-END:variables
}
